/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './index.tsx', './App.tsx', './components/**/*.{ts,tsx}', './context/**/*.{ts,tsx}', './hooks/**/*.{ts,tsx}', './pages/**/*.{ts,tsx}', './services/**/*.{ts,tsx}', './lib/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      colors: {
        surface: {
          page: 'var(--le-bg-page)',
          card: 'var(--le-bg-card)',
          muted: 'var(--le-bg-muted)',
          elevated: 'var(--le-bg-elevated)',
          border: 'var(--le-border)',
          'border-subtle': 'var(--le-border-subtle)',
        },
        content: {
          primary: 'var(--le-text)',
          muted: 'var(--le-text-muted)',
          faint: 'var(--le-text-faint)',
        },
        'brand-blue': '#0066CC',
        'brand-dark': '#0A1628',
        'brand-navy': '#0F2140',
        'brand-lightblue': '#E8F4FD',
        'brand-cyan': '#00B4D8',
        'brand-gray': '#F7F9FC',
        'brand-success': '#2A9D8F',
        'brand-orange': '#FF6B35',
        'brand-orange-light': '#FFF3ED',
        'brand-blue-50': '#EFF6FF',
        'brand-blue-100': '#DBEAFE',
        'brand-blue-500': '#0066CC',
        'brand-blue-600': '#0052A3',
        'brand-blue-700': '#003D7A',
        'brand-blue-800': '#002952',
        'brand-blue-900': '#0A1628',
      },
      boxShadow: {
        card: '0 4px 6px -1px rgb(0 0 0 / 0.07), 0 2px 4px -2px rgb(0 0 0 / 0.07)',
        'card-hover': '0 10px 15px -3px rgb(0 0 0 / 0.08), 0 4px 6px -4px rgb(0 0 0 / 0.08)',
      },
      borderRadius: {
        xl: '1rem',
        '2xl': '1.5rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out forwards',
        'slide-down': 'slideDown 0.3s ease-out forwards',
        'scale-in': 'scaleIn 0.2s ease-out',
        'bounce-in': 'bounceIn 0.4s ease-out',
        'shimmer': 'shimmer 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        bounceIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '50%': { transform: 'scale(1.02)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
    },
  },
  safelist: [
    'bg-surface-page',
    'bg-surface-card',
    'bg-surface-muted',
    'bg-surface-elevated',
    'text-content-primary',
    'text-content-muted',
    'text-content-faint',
    'border-surface-border',
    'border-surface-border-subtle',
    'shadow-card',
    /* Design system status colors */
    'bg-green-100', 'bg-green-500', 'text-green-700', 'border-green-200',
    'bg-blue-100', 'bg-brand-blue', 'text-blue-700', 'border-blue-200',
    'bg-orange-100', 'bg-orange-500', 'text-orange-700', 'border-orange-200',
    'bg-red-100', 'bg-red-500', 'text-red-700', 'border-red-200',
    'bg-slate-100', 'bg-slate-500', 'text-slate-700', 'border-slate-200',
    'dark:bg-green-950/40', 'dark:text-green-300', 'dark:border-green-800',
    'dark:bg-blue-950/40', 'dark:text-blue-300', 'dark:border-blue-800',
    'dark:bg-orange-950/40', 'dark:text-orange-300', 'dark:border-orange-800',
    'dark:bg-red-950/40', 'dark:text-red-300', 'dark:border-red-800',
    'dark:bg-slate-800', 'dark:text-slate-300', 'dark:border-slate-700',
  ],
  plugins: [],
};
