# Import all models here for Alembic autogenerate
from app.models.base import Base
from app.models.user import User, UserProfile, RefreshToken, PasswordResetToken
from app.models.customer import CustomerAddress
from app.models.partner import (
    Partner,
    PartnerLocation,
    PartnerDocument,
    PartnerOperatingHours,
    PartnerStaff,
)
from app.models.catalog import (
    ServiceCategory,
    ServiceType,
    PartnerService,
    PricingRule,
)
from app.models.order import (
    Order,
    OrderItem,
    OrderStatusHistory,
    OrderEvent,
    OrderAttachment,
)
from app.models.logistics import (
    Driver,
    DriverLocation,
    DeliveryTask,
)
from app.models.payment import (
    PaymentMethod,
    PaymentStatus,
    PaymentIntentStatus,
    PaymentTransactionStatus,
    PaymentTransactionType,
    PaymentProvider,
    RefundStatus,
    PaymentIntent,
    PaymentTransaction,
    PaymentProviderEvent,
    RefundRequest,
    RefundTransaction,
)
from app.models.dispute import (
    DisputeStatus,
    DisputeCategory,
    DisputeResolutionType,
    Dispute,
)
from app.models.commission import (
    CommissionStatus,
    CommissionRecord,
)
from app.models.notification import (
    Notification,
    NotificationDelivery,
    NotificationTemplate,
)
from app.models.notification_ops import (
    NotificationOpsItem,
    NotificationOpsTemplate,
    NotificationOpsAutomation,
    NotificationOpsSegment,
    NotificationOpsError,
    NotificationOpsUnsubscribe,
    NotificationOpsProviderHealth,
    NotificationOpsActivity,
)
from app.models.payment_gateway_ops import (
    PaymentGatewayProvider,
    PaymentGatewayTransaction,
    PaymentGatewayIncident,
    PaymentGatewaySettlement,
    PaymentGatewayWebhook,
    PaymentGatewayReconciliation,
    PaymentGatewayHealth,
    PaymentGatewayRefund,
    PaymentGatewayCashFlow,
)
from app.models.whatsapp_ops import (
    WhatsappConversation,
    WhatsappTemplate,
    WhatsappCampaign,
    WhatsappAutomation,
    WhatsappNotification,
    WhatsappWebhook,
    WhatsappQuality,
    WhatsappCostSnapshot,
    WhatsappAiMetrics,
    WhatsappSegment,
)
from app.models.sms_ops import (
    SmsProvider,
    SmsSender,
    SmsTemplate,
    SmsCampaign,
    SmsMessage,
    SmsCreditLedger,
    SmsLog,
    SmsOtpRecord,
    SmsAlert,
    SmsWebhook,
    SmsSettings,
)
from app.models.email_ops import (
    EmailTemplate,
    EmailCampaign,
    EmailAutomation,
    EmailMessage,
    EmailBounce,
    EmailUnsubscribe,
    EmailInvoiceLog,
    EmailDeliverability,
    EmailWebhook,
    EmailAlert,
    EmailSettings,
)
from app.models.integrations_ops import (
    IntegrationsApiKey,
    IntegrationsWebhook,
    IntegrationsWebhookDelivery,
    IntegrationsTrackingConfig,
    IntegrationsHealth,
    IntegrationsApiLog,
    IntegrationsAlert,
)
from app.models.admin_management_ops import (
    AdminMgmtUser,
    AdminMgmtRole,
    AdminMgmtPermission,
    AdminMgmtRolePermission,
    AdminMgmtInvitation,
    AdminMgmtSession,
    AdminMgmtActivityLog,
    AdminMgmtAuditLog,
    AdminMgmtSecurityAlert,
)
from app.models.activity_log_ops import ActivityLogEvent
from app.models.rbac_ops import (
    RbacRole,
    RbacPermission,
    RbacRolePermission,
    RbacUserRole,
    RbacUserPermission,
    RbacPermissionException,
    RbacTemporaryPermission,
    RbacPermissionAuditLog,
    RbacPermissionHistory,
    RbacRiskAlert,
    RbacSecurityPolicy,
    RbacTenant,
)
from app.models.promotion import (
    PromoDiscountType,
    PromoCode,
    PromoCodeUsage,
)
from app.models.content import (
    SiteContentConfig,
)
from app.models.subscription import (
    SubscriptionPlanConfig,
)
from app.models.tracking import (
    TrackingSettingsConfig,
)
from app.models.advertisement import (
    AdvertisementConfig,
)
from app.models.ad_analytics import (
    AdCampaign,
    Advertisement,
    AdImpression,
    AdClick,
    AdConversion,
    AdExperiment,
)
from app.models.loyalty import (
    LoyaltySettingsConfig,
    LoyaltyLedgerEntry,
    LoyaltyReward,
)
from app.models.order_addon import OrderAddOn
from app.models.referral import (
    ReferralSettingsConfig,
    ReferralReviewStatus,
    ReferralCampaign,
)
from app.models.marketing_campaign import (
    MarketingCampaign,
    MarketingAutomation,
)
from app.models.support import (
    SupportTicket,
    SupportTicketAttachment,
    ReviewStatus,
    SupportMessage,
    Review,
)
from app.models.claim import (
    Claim,
    ClaimEvent,
    ClaimNote,
    ClaimAttachment,
    ClaimEscalation,
    ClaimAssignment,
    ClaimSlaRule,
    ClaimRefund,
    ClaimCategory,
    ClaimStatusHistory,
    ClaimType,
    ClaimStatus,
    ClaimPriority,
    ClaimRefundStatus,
)
from app.models.cms import (
    CMSPage,
    CMSSection,
    CMSFAQ,
    CMSMedia,
    CMSNavigation,
    CMSTranslation,
    CMSRevision,
    CMSPublishHistory,
    CMSSEO,
    CMSTemplate,
    CMSBlock,
    CMSAnalytics,
    CMSPageType,
    CMSPageStatus,
)
from app.models.blog import (
    BlogPost,
    BlogCategory,
    BlogTag,
    BlogAuthor,
    BlogComment,
    BlogRevision,
    BlogView,
    BlogLike,
    BlogBookmark,
    BlogRelatedPost,
    BlogSEO,
    BlogAIContent,
    BlogAnalytics,
    BlogLead,
    BlogTranslation,
    BlogCalendar,
    BlogPostStatus,
    BlogCommentStatus,
    blog_post_tags,
)
from app.models.admin import (
    AuditLog,
    AdminNote,
)
from app.models.operational import (
    ProofType,
    ActorType,
    VerificationStatus,
    OperationalProof,
    TimelineEventType,
    OperationalTimeline,
)

# Export all models
__all__ = [
    "Base",
    "User",
    "UserProfile",
    "RefreshToken",
    "PasswordResetToken",
    "CustomerAddress",
    "Partner",
    "PartnerLocation",
    "PartnerDocument",
    "PartnerOperatingHours",
    "PartnerStaff",
    "ServiceCategory",
    "ServiceType",
    "PartnerService",
    "PricingRule",
    "Order",
    "OrderItem",
    "OrderStatusHistory",
    "OrderEvent",
    "OrderAttachment",
    "Driver",
    "DriverLocation",
    "DeliveryTask",
    "PaymentMethod",
    "PaymentStatus",
    "PaymentIntentStatus",
    "PaymentTransactionStatus",
    "PaymentTransactionType",
    "PaymentProvider",
    "RefundStatus",
    "PaymentIntent",
    "PaymentTransaction",
    "PaymentProviderEvent",
    "RefundRequest",
    "RefundTransaction",
    "DisputeStatus",
    "DisputeCategory",
    "DisputeResolutionType",
    "Dispute",
    "CommissionStatus",
    "CommissionRecord",
    "Notification",
    "NotificationDelivery",
    "NotificationTemplate",
    "PromoDiscountType",
    "PromoCode",
    "PromoCodeUsage",
    "SiteContentConfig",
    "SubscriptionPlanConfig",
    "TrackingSettingsConfig",
    "AdvertisementConfig",
    "LoyaltySettingsConfig",
    "LoyaltyLedgerEntry",
    "LoyaltyReward",
    "OrderAddOn",
    "ReferralSettingsConfig",
    "ReferralReviewStatus",
    "ReferralCampaign",
    "MarketingCampaign",
    "MarketingAutomation",
    "SupportTicket",
    "SupportTicketAttachment",
    "ReviewStatus",
    "SupportMessage",
    "Review",
    "Claim",
    "ClaimEvent",
    "ClaimNote",
    "ClaimAttachment",
    "ClaimEscalation",
    "ClaimAssignment",
    "ClaimSlaRule",
    "ClaimRefund",
    "ClaimCategory",
    "ClaimStatusHistory",
    "ClaimType",
    "ClaimStatus",
    "ClaimPriority",
    "ClaimRefundStatus",
    "CMSPage",
    "CMSSection",
    "CMSFAQ",
    "CMSMedia",
    "CMSNavigation",
    "CMSTranslation",
    "CMSRevision",
    "CMSPublishHistory",
    "CMSSEO",
    "CMSTemplate",
    "CMSBlock",
    "CMSAnalytics",
    "CMSPageType",
    "CMSPageStatus",
    "BlogPost",
    "BlogCategory",
    "BlogTag",
    "BlogAuthor",
    "BlogComment",
    "BlogRevision",
    "BlogView",
    "BlogLike",
    "BlogBookmark",
    "BlogRelatedPost",
    "BlogSEO",
    "BlogAIContent",
    "BlogAnalytics",
    "BlogLead",
    "BlogTranslation",
    "BlogCalendar",
    "BlogPostStatus",
    "BlogCommentStatus",
    "blog_post_tags",
    "AuditLog",
    "AdminNote",
    "ProofType",
    "ActorType",
    "VerificationStatus",
    "OperationalProof",
    "TimelineEventType",
    "OperationalTimeline",
    "AdCampaign",
    "Advertisement",
    "AdImpression",
    "AdClick",
    "AdConversion",
    "AdExperiment",
]
