import { AnomalyItem, AnomalySummary, SystemHealthItem, ImpactedCorridor, RevenueLeakageItem, AnomalyActivityEvent } from './anomalies-types';

export const MOCK_SUMMARY: AnomalySummary = {
  total: 7,
  critical: 2,
  major: 2,
  medium: 2,
  low: 1,
  financialImpact: 145,
  impactedOrders: 12,
  averageResolutionMinutes: 18,
  openInvestigations: 5,
};

export const MOCK_SYSTEM_HEALTH: SystemHealthItem[] = [
  { name: 'API', status: 'healthy', icon: 'cloud', lastChecked: new Date().toISOString() },
  { name: 'Database', status: 'healthy', icon: 'database', lastChecked: new Date().toISOString() },
  { name: 'Payments', status: 'healthy', icon: 'wallet', lastChecked: new Date().toISOString() },
  { name: 'WhatsApp', status: 'warning', icon: 'chatBubble', lastChecked: new Date().toISOString() },
  { name: 'SMS', status: 'healthy', icon: 'device-phone-mobile', lastChecked: new Date().toISOString() },
  { name: 'Logistics', status: 'healthy', icon: 'truck', lastChecked: new Date().toISOString() },
];

export const MOCK_CORRIDORS: ImpactedCorridor[] = [
  { corridor: 'order', label: 'Commandes', status: 'healthy', icon: 'shoppingBag', count: 0 },
  { corridor: 'payment', label: 'Paiements', status: 'critical', icon: 'currencyDollar', count: 2 },
  { corridor: 'logistics', label: 'Logistique', status: 'major', icon: 'truck', count: 3 },
  { corridor: 'marketplace', label: 'Marketplace', status: 'healthy', icon: 'building', count: 0 },
];

export const MOCK_ANOMALIES: AnomalyItem[] = [
  {
    id: 'ANO-001',
    title: 'Paiement orphelin',
    description: 'Paiement reçu sans commande associée',
    severity: 'critical',
    corridor: 'payment',
    reference: 'ORD-7841',
    impactLabel: '25,00 $',
    impactAmount: 25,
    currency: 'USD',
    detectedAt: '2026-06-07T16:49:00Z',
    partnerName: 'Prestige Pressing',
    clientName: 'Marie Kabongo',
    detectionConfidence: 97,
    status: 'open',
  },
  {
    id: 'ANO-002',
    title: 'Commande livrée sans preuve',
    description: 'Livraison sans photo de livraison',
    severity: 'critical',
    corridor: 'logistics',
    reference: 'ORD-9123',
    impactLabel: 'Client',
    detectedAt: '2026-06-07T16:47:00Z',
    partnerName: 'Speed Clean',
    driverName: 'Koffi A.',
    detectionConfidence: 94,
    status: 'open',
  },
  {
    id: 'ANO-003',
    title: 'Collecte sans chauffeur assigné',
    description: 'Collecte confirmée sans chauffeur',
    severity: 'major',
    corridor: 'logistics',
    reference: 'ORD-4451',
    impactLabel: 'Logistique',
    detectedAt: '2026-06-07T16:45:00Z',
    partnerName: 'Eco Pressing',
    zone: 'Gombe',
    detectionConfidence: 86,
    status: 'investigating',
  },
  {
    id: 'ANO-004',
    title: 'Double remboursement détecté',
    description: 'Remboursement automatique et manuel',
    severity: 'major',
    corridor: 'payment',
    reference: 'ORD-6621',
    impactLabel: '12,50 $',
    impactAmount: 12.5,
    currency: 'USD',
    detectedAt: '2026-06-07T16:42:00Z',
    partnerName: 'Prestige Pressing',
    clientName: 'Paul M.',
    detectionConfidence: 92,
    status: 'open',
  },
  {
    id: 'ANO-005',
    title: 'Livraison hors SLA',
    description: 'Livraison effectuée après dépassement SLA',
    severity: 'medium',
    corridor: 'logistics',
    reference: 'ORD-3312',
    impactLabel: 'SLA',
    detectedAt: '2026-06-07T16:39:00Z',
    driverName: 'David M.',
    zone: 'Limete',
    detectionConfidence: 81,
    status: 'open',
  },
  {
    id: 'ANO-006',
    title: 'Webhook dupliqué',
    description: 'Webhook reçu en double',
    severity: 'low',
    corridor: 'order',
    reference: 'WEB-7782',
    impactLabel: 'Système',
    detectedAt: '2026-06-07T16:19:00Z',
    source: 'Webhook',
    detectionConfidence: 99,
    status: 'resolved',
  },
  {
    id: 'ANO-007',
    title: 'Commission dupliquée',
    description: 'Commission calculée deux fois',
    severity: 'medium',
    corridor: 'logistics',
    reference: 'ORD-5534',
    impactLabel: '8,00 $',
    impactAmount: 8,
    currency: 'USD',
    detectedAt: '2026-06-07T16:29:00Z',
    partnerName: 'Quick Wash',
    driverName: 'Aline K.',
    detectionConfidence: 88,
    status: 'open',
  },
];

export const MOCK_REVENUE_LEAKAGE: RevenueLeakageItem[] = [
  { label: 'Paiements orphelins', amount: 50, color: 'text-red-500' },
  { label: 'Doubles paiements', amount: 25, color: 'text-orange-500' },
  { label: 'Commissions perdues', amount: 40, color: 'text-yellow-500' },
  { label: 'Litiges potentiels', amount: 30, color: 'text-purple-500' },
];

export const MOCK_ACTIVITY_FEED: AnomalyActivityEvent[] = [
  { id: 'EVT-1', time: '16:49', title: 'Paiement orphelin détecté', reference: 'ORD-7841', partner: 'Prestige Pressing', severity: 'critical' },
  { id: 'EVT-2', time: '16:47', title: 'Commande livrée sans preuve', reference: 'ORD-9123', partner: 'Speed Clean', severity: 'critical' },
  { id: 'EVT-3', time: '16:45', title: 'Collecte sans chauffeur', reference: 'ORD-4451', partner: 'Eco Pressing', severity: 'major' },
  { id: 'EVT-4', time: '16:42', title: 'Double remboursement détecté', reference: 'ORD-6621', partner: 'Prestige Pressing', severity: 'major' },
  { id: 'EVT-5', time: '16:39', title: 'Livraison hors SLA', reference: 'ORD-3312', partner: 'David M.', severity: 'medium' },
  { id: 'EVT-6', time: '16:19', title: 'Webhook dupliqué', reference: 'WEB-7782', severity: 'low' },
  { id: 'EVT-7', time: '16:29', title: 'Commission dupliquée', reference: 'ORD-5534', partner: 'Quick Wash', severity: 'medium' },
];
