import {
  DisputeRequest,
  DisputeSummary,
  DisputeBreakdownItem,
  DisputeStatusAmount,
  RefundTrendPoint,
  PartnerRefundRanking,
  RootCauseItem,
  DisputeSlaSummary,
  DisputeFinancialImpact,
  DisputeAnomaly,
  PlatformProtectionSummary,
  DisputeActivityEvent,
} from './disputes-types';

export const mockSummary: DisputeSummary = {
  totalRequests: 148,
  pending: 26,
  underReview: 18,
  approved: 72,
  rejected: 20,
  totalRequestedAmount: 2845,
  totalRefundedAmount: 1738,
  acceptanceRate: 78,
  currency: 'USD',
};

export const mockPartnerNames = [
  'Prestige Pressing',
  'Speed Clean',
  'Eco Wash',
  'Quick Wash',
  'Clean & Go',
];

export const mockDisputeRequests: DisputeRequest[] = [
  {
    id: 'REF-1487',
    orderId: 'ORD-7845',
    clientName: 'Marie Kabongo',
    partnerName: 'Prestige Pressing',
    amount: 27,
    currency: 'USD',
    type: 'quality',
    status: 'pending',
    severity: 'medium',
    requestedAt: '2026-06-07T10:35:00Z',
    reason: 'Taches persistantes sur chemises blanches après nettoyage',
    evidenceCount: 3,
    truthScore: 82,
    assignedTo: 'Support Kim',
    timeline: [
      { id: 't1', type: 'created', label: 'Demande créée', detail: 'Ouverture du litige qualité', timestamp: '2026-06-07T10:35:00Z', actor: 'Marie Kabongo' },
    ],
    notes: [{ id: 'n1', author: 'Support Kim', role: 'Support', content: 'Photos reçues, en attente validation partenaire', createdAt: '2026-06-07T11:00:00Z' }],
    anomalies: [],
  },
  {
    id: 'REF-1486',
    orderId: 'ORD-7841',
    clientName: 'Jean Pierre',
    partnerName: 'Speed Clean',
    driverName: 'Patrick Ilunga',
    amount: 32.5,
    currency: 'USD',
    type: 'delay',
    status: 'under_review',
    severity: 'major',
    requestedAt: '2026-06-07T09:12:00Z',
    reason: 'Livraison retardée de 48h par rapport au délai promis',
    evidenceCount: 2,
    truthScore: 91,
    assignedTo: 'Support Serge',
    timeline: [
      { id: 't1', type: 'created', label: 'Demande créée', detail: 'Retard signalé', timestamp: '2026-06-07T09:12:00Z', actor: 'Jean Pierre' },
      { id: 't2', type: 'status_change', label: 'En cours d\'examen', detail: 'Assigné à Support Serge', timestamp: '2026-06-07T09:30:00Z', actor: 'Système' },
    ],
    anomalies: ['Livraison hors SLA'],
  },
  {
    id: 'REF-1485',
    orderId: 'ORD-7838',
    clientName: 'Sandra M.',
    partnerName: 'Eco Wash',
    amount: 18,
    currency: 'USD',
    type: 'missing_item',
    status: 'under_review',
    severity: 'medium',
    requestedAt: '2026-06-06T21:44:00Z',
    reason: 'Une paire de chaussettes manquante dans la commande',
    evidenceCount: 4,
    truthScore: 95,
    assignedTo: 'Support Kim',
    anomalies: [],
  },
  {
    id: 'REF-1484',
    orderId: 'ORD-7832',
    clientName: 'David L.',
    partnerName: 'Quick Wash',
    amount: 41,
    currency: 'USD',
    type: 'cancellation',
    status: 'approved',
    severity: 'low',
    requestedAt: '2026-06-06T18:03:00Z',
    reason: 'Annulation client avant collecte, frais prélevés à tort',
    evidenceCount: 2,
    truthScore: 88,
    resolvedAt: '2026-06-06T19:00:00Z',
    anomalies: [],
  },
  {
    id: 'REF-1483',
    orderId: 'ORD-7829',
    clientName: 'Grace N.',
    partnerName: 'Clean & Go',
    amount: 22,
    currency: 'USD',
    type: 'quality',
    status: 'rejected',
    severity: 'low',
    requestedAt: '2026-06-06T16:20:00Z',
    reason: 'Qualité jugée insuffisante — preuves non concluantes',
    evidenceCount: 1,
    truthScore: 35,
    resolvedAt: '2026-06-06T17:15:00Z',
    anomalies: [],
  },
  {
    id: 'REF-1482',
    orderId: 'ORD-7827',
    clientName: 'Alain T.',
    partnerName: 'Prestige Pressing',
    amount: 15.5,
    currency: 'USD',
    type: 'delay',
    status: 'pending',
    severity: 'medium',
    requestedAt: '2026-06-06T14:11:00Z',
    reason: 'Retard de livraison express non respecté',
    evidenceCount: 2,
    truthScore: 76,
    anomalies: [],
  },
  {
    id: 'REF-1481',
    orderId: 'ORD-7823',
    clientName: 'Patricia B.',
    partnerName: 'Eco Wash',
    amount: 26,
    currency: 'USD',
    type: 'duplicate_payment',
    status: 'approved',
    severity: 'critical',
    requestedAt: '2026-06-06T11:02:00Z',
    reason: 'Double débit Mobile Money pour la même commande',
    evidenceCount: 5,
    truthScore: 98,
    resolvedAt: '2026-06-06T12:30:00Z',
    anomalies: ['Paiement orphelin'],
  },
  {
    id: 'REF-1480',
    orderId: 'ORD-7819',
    clientName: 'Catherine K.',
    partnerName: 'Speed Clean',
    amount: 19,
    currency: 'USD',
    type: 'damaged_item',
    status: 'rejected',
    severity: 'low',
    requestedAt: '2026-06-05T19:53:00Z',
    reason: 'Article abîmé — usure préexistante visible sur photos',
    evidenceCount: 1,
    truthScore: 22,
    resolvedAt: '2026-06-05T21:00:00Z',
    anomalies: [],
  },
  {
    id: 'REF-1479',
    orderId: 'ORD-7815',
    clientName: 'Franck M.',
    partnerName: 'Quick Wash',
    amount: 33,
    currency: 'USD',
    type: 'cancellation',
    status: 'pending',
    severity: 'medium',
    requestedAt: '2026-06-05T15:31:00Z',
    reason: 'Commande annulée mais frais de collecte facturés',
    evidenceCount: 2,
    truthScore: 70,
    anomalies: [],
  },
  {
    id: 'REF-1478',
    orderId: 'ORD-7812',
    clientName: 'Mireille D.',
    partnerName: 'Clean & Go',
    amount: 21,
    currency: 'USD',
    type: 'quality',
    status: 'under_review',
    severity: 'major',
    requestedAt: '2026-06-05T13:05:00Z',
    reason: 'Nettoyage à sec insatisfaisant sur costume',
    evidenceCount: 3,
    truthScore: 84,
    assignedTo: 'Support Serge',
    anomalies: [],
  },
];

export const mockBreakdown: DisputeBreakdownItem[] = [
  { name: 'Qualité', count: 46, percentage: 31, color: '#3b82f6' },
  { name: 'Retard', count: 32, percentage: 22, color: '#f59e0b' },
  { name: 'Annulation', count: 24, percentage: 16, color: '#8b5cf6' },
  { name: 'Article manquant', count: 18, percentage: 12, color: '#10b981' },
  { name: 'Paiement', count: 14, percentage: 9, color: '#ef4444' },
  { name: 'Autres', count: 14, percentage: 9, color: '#94a3b8' },
];

export const mockStatusAmounts: DisputeStatusAmount[] = [
  { label: 'Approuvés', amount: 1738, percentage: 61, color: '#22c55e' },
  { label: 'En attente', amount: 512, percentage: 18, color: '#f59e0b' },
  { label: 'En cours', amount: 395, percentage: 14, color: '#3b82f6' },
  { label: 'Rejetées', amount: 200, percentage: 7, color: '#ef4444' },
];

export const mockTrend: RefundTrendPoint[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date(2026, 4, 9 + i);
  const base = 35 + Math.sin(i * 0.4) * 15;
  const variation = (i % 5) * 8;
  return {
    date: date.toISOString().split('T')[0],
    amount: Math.round(base + variation),
  };
});

export const mockPartnerRanking: PartnerRefundRanking[] = [
  { name: 'Prestige Pressing', requests: 32, amount: 562, acceptanceRate: 81 },
  { name: 'Speed Clean', requests: 28, amount: 418, acceptanceRate: 75 },
  { name: 'Eco Wash', requests: 24, amount: 356, acceptanceRate: 79 },
  { name: 'Quick Wash', requests: 22, amount: 258, acceptanceRate: 72 },
  { name: 'Clean & Go', requests: 18, amount: 144, acceptanceRate: 78 },
];

export const mockRootCauses: RootCauseItem[] = [
  { name: 'Qualité du nettoyage', percentage: 31, icon: 'sparkles', color: '#3b82f6' },
  { name: 'Retard de livraison', percentage: 22, icon: 'truck', color: '#f59e0b' },
  { name: 'Annulation client', percentage: 16, icon: 'xmark', color: '#8b5cf6' },
  { name: 'Article manquant', percentage: 12, icon: 'shoppingBag', color: '#10b981' },
  { name: 'Paiement double', percentage: 9, icon: 'credit-card', color: '#ef4444' },
  { name: 'Article abîmé', percentage: 6, icon: 'warning', color: '#f97316' },
  { name: 'Autres', percentage: 4, icon: 'document-text', color: '#94a3b8' },
];

export const mockSla: DisputeSlaSummary = {
  inTime: 138,
  inTimePercent: 92,
  atRisk: 9,
  atRiskPercent: 6,
  outOfSla: 3,
  outOfSlaPercent: 2,
};

export const mockFinancialImpact: DisputeFinancialImpact = {
  requested: 2845,
  refunded: 1738,
  saved: 1107,
  netCostPercent: 1.2,
};

export const mockAnomalies: DisputeAnomaly[] = [
  { name: 'Paiement orphelin', count: 2 },
  { name: 'Commande bloquée', count: 1 },
  { name: 'Collecte sans preuve', count: 3 },
  { name: 'Livraison hors SLA', count: 1 },
  { name: 'Commission manquante', count: 2 },
];

export const mockProtection: PlatformProtectionSummary = {
  fraudDetection: true,
  protectionRules: 14,
  limitsConfigured: 8,
  autoValidation: true,
};

export const mockActivity: DisputeActivityEvent[] = [
  {
    id: 'EVT-001',
    time: '10:35',
    action: 'Nouvelle demande REF-1487',
    detail: 'Pour ORD-7845 — Marie Kabongo',
    icon: 'document-text',
    color: 'amber',
  },
  {
    id: 'EVT-002',
    time: '09:12',
    action: 'Remboursement approuvé REF-1481',
    detail: '26,00 $ — Paiement double',
    icon: 'check',
    color: 'green',
  },
  {
    id: 'EVT-003',
    time: '08:45',
    action: 'Litige rejeté REF-1476',
    detail: 'Article conforme — preuves insuffisantes',
    icon: 'xmark',
    color: 'red',
  },
  {
    id: 'EVT-004',
    time: '07:30',
    action: 'Litige en cours REF-1486',
    detail: 'Retard livraison — Speed Clean',
    icon: 'arrow-path',
    color: 'blue',
  },
  {
    id: 'EVT-005',
    time: '06:15',
    action: 'Remboursement approuvé REF-1473',
    detail: '18,00 $ — Article manquant',
    icon: 'check',
    color: 'green',
  },
];
