import { TruthDashboardData } from './truth-dashboard-types';

export const truthDashboardFixture: TruthDashboardData = {
  summary: {
    truthScore: 97.8,
    lastCheckedAt: '2026-06-07T16:24:03',
    ordersVerifiedRate: 98.4,
    paymentsVerifiedRate: 99.8,
    pickupsVerifiedRate: 97.1,
    deliveriesVerifiedRate: 96.8,
    proofsCompleteRate: 98.6,
    openAnomalies: 18,
    openInvestigations: 5,
    potentialLeakageAmount: 485,
    currency: 'USD',
  },
  corridors: [
    {
      id: 'order',
      title: 'Order Corridor',
      icon: 'shoppingBag',
      tone: 'bg-blue-50 text-blue-700 border-blue-100',
      primaryMetricLabel: 'Orders traitees',
      primaryMetricValue: '12 584',
      status: 'healthy',
      rows: [
        { label: 'Anomalies', value: 3, severity: 'danger' },
        { label: 'Risque', value: 'Faible', severity: 'success' },
        { label: 'Dernier incident', value: '12 min', severity: 'neutral' },
      ],
    },
    {
      id: 'payment',
      title: 'Payment Corridor',
      icon: 'currencyDollar',
      tone: 'bg-green-50 text-green-700 border-green-100',
      primaryMetricLabel: 'Transactions',
      primaryMetricValue: '14 892',
      status: 'warning',
      rows: [
        { label: 'Paiements orphelins', value: 2, severity: 'warning' },
        { label: 'Double paiement', value: 0, severity: 'success' },
        { label: 'Remboursements suspects', value: 1, severity: 'danger' },
      ],
    },
    {
      id: 'logistics',
      title: 'Logistics Corridor',
      icon: 'truck',
      tone: 'bg-orange-50 text-orange-700 border-orange-100',
      primaryMetricLabel: 'Collectes',
      primaryMetricValue: '12 001',
      status: 'critical',
      rows: [
        { label: 'Livraisons', value: '11 944', severity: 'neutral' },
        { label: 'Retards SLA', value: 18, severity: 'danger' },
        { label: 'Missions sans preuve', value: 2, severity: 'danger' },
      ],
    },
    {
      id: 'marketplace',
      title: 'Marketplace Corridor',
      icon: 'building',
      tone: 'bg-purple-50 text-purple-700 border-purple-100',
      primaryMetricLabel: 'Partenaires actifs',
      primaryMetricValue: 143,
      status: 'warning',
      rows: [
        { label: 'Partenaires suspendus', value: 2, severity: 'danger' },
        { label: 'Commandes litigieuses', value: 4, severity: 'danger' },
      ],
    },
  ],
  anomalies: [
    { id: 'ANO-1', title: 'Paiement recu sans commande', description: 'Paiement orphelin detecte dans le systeme', severity: 'critical', cases: 3 },
    { id: 'ANO-2', title: 'Commande livree sans preuve', description: 'Livraison effectuee sans photo de livraison', severity: 'critical', cases: 2 },
    { id: 'ANO-3', title: 'Collecte sans chauffeur assigne', description: 'Collecte confirmee sans chauffeur assigne', severity: 'major', cases: 1 },
    { id: 'ANO-4', title: 'Double remboursement detecte', description: 'Remboursement automatique et manuel', severity: 'major', cases: 1 },
    { id: 'ANO-5', title: 'Partenaire hors SLA', description: 'Partenaire au-dessus du delai contractuel', severity: 'minor', cases: 5 },
  ],
  violations: [
    { id: 'VIO-1', severity: 'critical', type: 'Payment Orphan', reference: 'ORD-7845', impact: '25.00 $', detectedAt: '16:02', status: 'Nouveau' },
    { id: 'VIO-2', severity: 'critical', type: 'Delivery Without Proof', reference: 'ORD-9123', impact: 'Client', detectedAt: '15:45', status: 'Nouveau' },
    { id: 'VIO-3', severity: 'major', type: 'Missing GPS', reference: 'ORD-4451', impact: 'Logistique', detectedAt: '14:22', status: 'En cours' },
    { id: 'VIO-4', severity: 'major', type: 'Commission manquante', reference: 'ORD-6678', impact: '12.50 $', detectedAt: '12:10', status: 'Nouveau' },
    { id: 'VIO-5', severity: 'minor', type: 'Collecte hors creneau', reference: 'ORD-3210', impact: 'SLA', detectedAt: '11:55', status: 'Résolu' },
  ],
  investigations: [
    { id: 'INV-284', title: 'Paiement orphelin', orderReference: 'ORD-7845', detail: 'Paiement orphelin', assignedTo: 'Jean Admin', openedAt: '2026-06-07T15:58:00', severity: 'critical', status: 'in_progress' },
    { id: 'INV-285', title: 'Livraison sans photo', orderReference: 'ORD-9123', detail: 'Livraison sans photo', assignedTo: 'Support Ops', openedAt: '2026-06-07T15:40:00', severity: 'critical', status: 'in_progress' },
    { id: 'INV-286', title: 'Commission manquante', orderReference: 'ORD-6621', detail: 'Commission manquante', assignedTo: 'Finance', openedAt: '2026-06-07T14:32:00', severity: 'major', status: 'in_progress' },
    { id: 'INV-287', title: 'GPS incoherent', orderReference: 'ORD-3312', detail: 'GPS incoherent', assignedTo: 'Logistique', openedAt: '2026-06-07T13:22:00', severity: 'minor', status: 'resolved' },
    { id: 'INV-288', title: 'Partenaire hors SLA', orderReference: 'ORD-5544', detail: 'Partenaire hors SLA', assignedTo: 'Ops', openedAt: '2026-06-07T12:12:00', severity: 'minor', status: 'in_progress' },
  ],
  revenueLeakage: [
    { label: 'Paiements orphelins', amount: 230, tone: 'bg-red-50 text-red-700 border-red-100' },
    { label: 'Commissions manquantes', amount: 120, tone: 'bg-orange-50 text-orange-700 border-orange-100' },
    { label: 'Remboursements suspects', amount: 80, tone: 'bg-yellow-50 text-yellow-700 border-yellow-100' },
    { label: 'Collectes non facturees', amount: 55, tone: 'bg-blue-50 text-blue-700 border-blue-100' },
  ],
  revenueTrend: [32, 45, 37, 58, 42, 67, 61],
  sla: { within: 94, atRisk: 5, breached: 1 },
  activityFeed: [
    { time: '16:22', title: 'Anomalie detectee', detail: 'Paiement recu sans commande', reference: 'ORD-7741', severity: 'critical' },
    { time: '16:15', title: 'Preuve uploadee', detail: 'Photo de livraison ajoutee', reference: 'ORD-7823', severity: 'success' },
    { time: '16:08', title: 'Collecte effectuee', detail: 'Koffi A. · GPS valide', reference: 'ORD-7834', severity: 'success' },
    { time: '16:04', title: 'Chauffeur assigne', detail: 'Koffi A. · Moto KN-25-AB', reference: 'ORD-7834', severity: 'info' },
    { time: '16:02', title: 'Paiement recu', detail: '27.00 $ via Mobile Money', reference: 'ORD-7834', severity: 'info' },
  ],
};
