"""Add missing foreign keys to order models

Revision ID: 05dc81e265f7
Revises: initial
Create Date: 2026-03-14 23:26:39.310136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05dc81e265f7'
down_revision = 'initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_attachments', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_events', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'partner_services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'order_status_history', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'customer_addresses', ['pickup_address_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'partners', ['partner_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'customer_addresses', ['delivery_address_id'], ['id'])
    op.create_foreign_key(None, 'partner_documents', 'partners', ['partner_id'], ['id'])
    op.create_foreign_key(None, 'partner_locations', 'partners', ['partner_id'], ['id'])
    op.create_foreign_key(None, 'partner_operating_hours', 'partners', ['partner_id'], ['id'])
    op.create_foreign_key(None, 'partner_services', 'service_types', ['service_type_id'], ['id'])
    op.create_foreign_key(None, 'partner_services', 'partners', ['partner_id'], ['id'])
    op.create_foreign_key(None, 'partner_staff', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'partner_staff', 'partners', ['partner_id'], ['id'])
    op.drop_constraint('password_reset_tokens_token_hash_key', 'password_reset_tokens', type_='unique')
    op.create_foreign_key(None, 'pricing_rules', 'partner_services', ['service_id'], ['id'])
    op.drop_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', type_='unique')
    op.create_foreign_key(None, 'service_types', 'service_categories', ['category_id'], ['id'])
    op.drop_constraint('user_profiles_user_id_key', 'user_profiles', type_='unique')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_unique_constraint('user_profiles_user_id_key', 'user_profiles', ['user_id'])
    op.drop_constraint(None, 'service_types', type_='foreignkey')
    op.create_unique_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', ['token_hash'])
    op.drop_constraint(None, 'pricing_rules', type_='foreignkey')
    op.create_unique_constraint('password_reset_tokens_token_hash_key', 'password_reset_tokens', ['token_hash'])
    op.drop_constraint(None, 'partner_staff', type_='foreignkey')
    op.drop_constraint(None, 'partner_staff', type_='foreignkey')
    op.drop_constraint(None, 'partner_services', type_='foreignkey')
    op.drop_constraint(None, 'partner_services', type_='foreignkey')
    op.drop_constraint(None, 'partner_operating_hours', type_='foreignkey')
    op.drop_constraint(None, 'partner_locations', type_='foreignkey')
    op.drop_constraint(None, 'partner_documents', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'order_status_history', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_events', type_='foreignkey')
    op.drop_constraint(None, 'order_attachments', type_='foreignkey')
    # ### end Alembic commands ###