"""create_driver_dispatch_tables

Revision ID: 79dde77c97d6
Revises: 9bdf5a02252b
Create Date: 2026-03-15 07:57:45.880799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79dde77c97d6'
down_revision = '9bdf5a02252b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_tasks', sa.Column('task_type', sa.Enum('PICKUP', 'DELIVERY', name='tasktype'), nullable=False))
    op.add_column('delivery_tasks', sa.Column('pickup_location_type', sa.Enum('CUSTOMER', 'PARTNER', name='locationtype'), nullable=True))
    op.add_column('delivery_tasks', sa.Column('dropoff_location_type', sa.Enum('CUSTOMER', 'PARTNER', name='locationtype'), nullable=True))
    op.add_column('delivery_tasks', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_tasks', sa.Column('proof_photo_url', sa.String(length=500), nullable=True))
    op.add_column('delivery_tasks', sa.Column('proof_note', sa.Text(), nullable=True))
    # Convertir les valeurs existantes de status vers le nouvel enum
    # D'abord créer l'enum
    deliverytaskstatus = sa.Enum('PENDING', 'ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='deliverytaskstatus')
    deliverytaskstatus.create(op.get_bind(), checkfirst=True)
    
    # Mapper les anciennes valeurs aux nouvelles
    op.execute("""
        UPDATE delivery_tasks 
        SET status = 
            CASE 
                WHEN status = 'pending' THEN 'PENDING'
                WHEN status = 'assigned' THEN 'ASSIGNED'
                WHEN status = 'picked_up' THEN 'IN_PROGRESS'
                WHEN status = 'in_transit' THEN 'IN_PROGRESS'
                WHEN status = 'delivered' THEN 'COMPLETED'
                WHEN status = 'cancelled' THEN 'CANCELLED'
                ELSE 'PENDING'
            END
    """)
    
    # Maintenant changer le type de colonne
    op.alter_column('delivery_tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=deliverytaskstatus,
               postgresql_using='status::deliverytaskstatus',
               existing_nullable=False)
    op.drop_index('ix_delivery_tasks_order_id', table_name='delivery_tasks')
    op.create_index(op.f('ix_delivery_tasks_order_id'), 'delivery_tasks', ['order_id'], unique=False)
    op.create_foreign_key(None, 'delivery_tasks', 'drivers', ['driver_id'], ['id'])
    op.drop_column('delivery_tasks', 'delivered_at')
    op.drop_column('delivery_tasks', 'picked_up_at')
    op.add_column('driver_locations', sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key(None, 'driver_locations', 'drivers', ['driver_id'], ['id'])
    op.drop_column('driver_locations', 'speed')
    op.drop_column('driver_locations', 'accuracy')
    op.add_column('drivers', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='driverstatus'), nullable=False))
    op.add_column('drivers', sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=False))
    op.add_column('drivers', sa.Column('rating_count', sa.Integer(), nullable=False))
    op.drop_column('drivers', 'is_active')
    op.drop_column('drivers', 'vehicle_plate')
    op.create_foreign_key(None, 'notification_deliveries', 'notifications', ['notification_id'], ['id'])
    op.create_foreign_key(None, 'payment_provider_events', 'payment_intents', ['payment_intent_id'], ['id'])
    op.create_foreign_key(None, 'payment_transactions', 'payment_intents', ['payment_intent_id'], ['id'])
    op.create_foreign_key(None, 'refunds', 'payment_intents', ['payment_intent_id'], ['id'])
    op.create_foreign_key(None, 'support_messages', 'support_tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'support_messages', type_='foreignkey')
    op.drop_constraint(None, 'refunds', type_='foreignkey')
    op.drop_constraint(None, 'payment_transactions', type_='foreignkey')
    op.drop_constraint(None, 'payment_provider_events', type_='foreignkey')
    op.drop_constraint(None, 'notification_deliveries', type_='foreignkey')
    op.add_column('drivers', sa.Column('vehicle_plate', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('drivers', 'rating_count')
    op.drop_column('drivers', 'rating_avg')
    op.drop_column('drivers', 'status')
    op.add_column('driver_locations', sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('driver_locations', sa.Column('speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'driver_locations', type_='foreignkey')
    op.drop_column('driver_locations', 'recorded_at')
    op.add_column('delivery_tasks', sa.Column('picked_up_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('delivery_tasks', sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'delivery_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_delivery_tasks_order_id'), table_name='delivery_tasks')
    op.create_index('ix_delivery_tasks_order_id', 'delivery_tasks', ['order_id'], unique=False)
    op.alter_column('delivery_tasks', 'status',
               existing_type=sa.Enum('PENDING', 'ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='deliverytaskstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('delivery_tasks', 'proof_note')
    op.drop_column('delivery_tasks', 'proof_photo_url')
    op.drop_column('delivery_tasks', 'completed_at')
    op.drop_column('delivery_tasks', 'started_at')
    op.drop_column('delivery_tasks', 'scheduled_at')
    op.drop_column('delivery_tasks', 'dropoff_location_type')
    op.drop_column('delivery_tasks', 'pickup_location_type')
    op.drop_column('delivery_tasks', 'task_type')
    # ### end Alembic commands ###