"""Create pricing engine tables

Revision ID: 9bdf5a02252b
Revises: d8c7c8e810cf
Create Date: 2026-03-15 00:59:16.477515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdf5a02252b'
down_revision = 'd8c7c8e810cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Créer les types enum d'abord
    op.execute("CREATE TYPE pricingmode AS ENUM ('UNIT', 'KG', 'FIXED')")
    op.execute("CREATE TYPE ruletype AS ENUM ('EXPRESS_SURCHARGE', 'FRAGILE_FABRIC_SURCHARGE', 'BULK_DISCOUNT', 'MINIMUM_ORDER_FEE', 'PICKUP_FEE', 'DELIVERY_FEE')")
    op.execute("CREATE TYPE priceadjustmenttype AS ENUM ('FIXED', 'PERCENTAGE')")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_services', sa.Column('service_category_id', sa.UUID(), nullable=False))
    op.add_column('partner_services', sa.Column('pricing_mode', sa.Enum('UNIT', 'KG', 'FIXED', name='pricingmode', create_type=False), nullable=False))
    op.add_column('partner_services', sa.Column('estimated_turnaround_hours', sa.Integer(), nullable=False))
    op.alter_column('partner_services', 'base_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_partner_services_service_category_id'), 'partner_services', ['service_category_id'], unique=False)
    op.create_foreign_key('partner_services_service_category_id_fkey', 'partner_services', 'service_categories', ['service_category_id'], ['id'])
    op.drop_column('partner_services', 'unit')
    op.drop_column('partner_services', 'estimated_duration_minutes')
    op.drop_column('partner_services', 'is_active')
    op.drop_column('partner_services', 'currency')
    op.drop_column('partner_services', 'name')
    op.drop_column('partner_services', 'description')
    op.add_column('pricing_rules', sa.Column('partner_id', sa.UUID(), nullable=False))
    op.add_column('pricing_rules', sa.Column('rule_type', sa.Enum('EXPRESS_SURCHARGE', 'FRAGILE_FABRIC_SURCHARGE', 'BULK_DISCOUNT', 'MINIMUM_ORDER_FEE', 'PICKUP_FEE', 'DELIVERY_FEE', name='ruletype', create_type=False), nullable=False))
    op.add_column('pricing_rules', sa.Column('service_category_id', sa.UUID(), nullable=True))
    op.add_column('pricing_rules', sa.Column('service_type_id', sa.UUID(), nullable=True))
    op.add_column('pricing_rules', sa.Column('price_adjustment_type', sa.Enum('FIXED', 'PERCENTAGE', name='priceadjustmenttype', create_type=False), nullable=False))
    op.add_column('pricing_rules', sa.Column('price_adjustment_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('pricing_rules', 'min_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('pricing_rules', 'max_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('ix_pricing_rules_service_id', table_name='pricing_rules')
    op.create_index(op.f('ix_pricing_rules_partner_id'), 'pricing_rules', ['partner_id'], unique=False)
    op.drop_constraint('pricing_rules_service_id_fkey', 'pricing_rules', type_='foreignkey')
    op.create_foreign_key('pricing_rules_service_category_id_fkey', 'pricing_rules', 'service_categories', ['service_category_id'], ['id'])
    op.create_foreign_key('pricing_rules_service_type_id_fkey', 'pricing_rules', 'service_types', ['service_type_id'], ['id'])
    op.create_foreign_key('pricing_rules_partner_id_fkey', 'pricing_rules', 'partners', ['partner_id'], ['id'])
    op.drop_column('pricing_rules', 'price')
    op.drop_column('pricing_rules', 'time_start')
    op.drop_column('pricing_rules', 'service_id')
    op.drop_column('pricing_rules', 'price_type')
    op.drop_column('pricing_rules', 'time_end')
    op.drop_column('pricing_rules', 'day_of_week')
    op.add_column('service_categories', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_service_categories_slug'), 'service_categories', ['slug'], unique=True)
    op.drop_column('service_categories', 'display_order')
    op.drop_column('service_categories', 'icon')
    op.add_column('service_types', sa.Column('slug', sa.String(length=100), nullable=False))
    op.drop_index('ix_service_types_category_id', table_name='service_types')
    op.drop_index('ix_service_types_name', table_name='service_types')
    op.create_index(op.f('ix_service_types_name'), 'service_types', ['name'], unique=True)
    op.create_index(op.f('ix_service_types_slug'), 'service_types', ['slug'], unique=True)
    op.drop_constraint('service_types_category_id_fkey', 'service_types', type_='foreignkey')
    op.drop_column('service_types', 'category_id')
    op.drop_column('service_types', 'display_order')
    op.drop_column('service_types', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_types', sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('service_types', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('service_types', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('service_types_category_id_fkey', 'service_types', 'service_categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_service_types_slug'), table_name='service_types')
    op.drop_index(op.f('ix_service_types_name'), table_name='service_types')
    op.create_index('ix_service_types_name', 'service_types', ['name'], unique=False)
    op.create_index('ix_service_types_category_id', 'service_types', ['category_id'], unique=False)
    op.drop_column('service_types', 'slug')
    op.add_column('service_categories', sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('service_categories', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_service_categories_slug'), table_name='service_categories')
    op.drop_column('service_categories', 'slug')
    op.add_column('pricing_rules', sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pricing_rules', sa.Column('time_end', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('pricing_rules', sa.Column('price_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('pricing_rules', sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('pricing_rules', sa.Column('time_start', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('pricing_rules', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('pricing_rules_partner_id_fkey', 'pricing_rules', type_='foreignkey')
    op.drop_constraint('pricing_rules_service_type_id_fkey', 'pricing_rules', type_='foreignkey')
    op.drop_constraint('pricing_rules_service_category_id_fkey', 'pricing_rules', type_='foreignkey')
    op.create_foreign_key('pricing_rules_service_id_fkey', 'pricing_rules', 'partner_services', ['service_id'], ['id'])
    op.drop_index(op.f('ix_pricing_rules_partner_id'), table_name='pricing_rules')
    op.create_index('ix_pricing_rules_service_id', 'pricing_rules', ['service_id'], unique=False)
    op.alter_column('pricing_rules', 'max_quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('pricing_rules', 'min_quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('pricing_rules', 'price_adjustment_value')
    op.drop_column('pricing_rules', 'price_adjustment_type')
    op.drop_column('pricing_rules', 'service_type_id')
    op.drop_column('pricing_rules', 'service_category_id')
    op.drop_column('pricing_rules', 'rule_type')
    op.drop_column('pricing_rules', 'partner_id')
    op.add_column('partner_services', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('partner_services', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('partner_services', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('partner_services', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('partner_services', sa.Column('estimated_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('partner_services', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint('partner_services_service_category_id_fkey', 'partner_services', type_='foreignkey')
    op.drop_index(op.f('ix_partner_services_service_category_id'), table_name='partner_services')
    op.alter_column('partner_services', 'base_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('partner_services', 'estimated_turnaround_hours')
    op.drop_column('partner_services', 'pricing_mode')
    op.drop_column('partner_services', 'service_category_id')
    
    # Supprimer les types enum
    op.execute("DROP TYPE IF EXISTS priceadjustmenttype")
    op.execute("DROP TYPE IF EXISTS ruletype")
    op.execute("DROP TYPE IF EXISTS pricingmode")
    # ### end Alembic commands ###
