"""describe_changes

Revision ID: 9e87723373ba
Revises: 05dc81e265f7
Create Date: 2026-03-14 23:42:08.896539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e87723373ba'
down_revision = '05dc81e265f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###