"""add_payment_truth_corridor

Revision ID: add_payment_truth_corridor
Revises: add_logistics_truth_corridor
Create Date: 2026-06-03 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_payment_truth_corridor'
down_revision = 'add_logistics_truth_corridor'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. PaymentIntent : Float -> Numeric(10,2)
    op.alter_column('payment_intents', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               postgresql_using='amount::numeric(10,2)')
    op.alter_column('payment_intents', 'amount_expected',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               postgresql_using='amount_expected::numeric(10,2)')
    op.alter_column('payment_intents', 'amount_paid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               postgresql_using='amount_paid::numeric(10,2)')

    # 2. PaymentTransaction : Float -> Numeric(10,2)
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               postgresql_using='amount::numeric(10,2)')

    # 3. RefundRequest : Float -> Numeric(10,2)
    op.alter_column('refund_requests', 'requested_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               postgresql_using='requested_amount::numeric(10,2)')
    op.alter_column('refund_requests', 'approved_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               postgresql_using='approved_amount::numeric(10,2)')

    # 4. RefundTransaction : Float -> Numeric(10,2)
    op.alter_column('refund_transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               postgresql_using='amount::numeric(10,2)')

    # 5. CHECK constraints PaymentIntent
    op.create_check_constraint('ck_payment_intent_amount_paid_lte_expected', 'payment_intents', sa.text('amount_paid <= amount_expected'))
    op.create_check_constraint('ck_payment_intent_amount_expected_nonneg', 'payment_intents', sa.text('amount_expected >= 0'))
    op.create_check_constraint('ck_payment_intent_amount_paid_nonneg', 'payment_intents', sa.text('amount_paid >= 0'))

    # 6. CHECK constraints RefundRequest
    op.create_check_constraint('ck_refund_request_requested_amount_nonneg', 'refund_requests', sa.text('requested_amount >= 0'))
    op.create_check_constraint('ck_refund_request_approved_amount_lte_requested', 'refund_requests', sa.text('approved_amount IS NULL OR approved_amount <= requested_amount'))
    op.create_check_constraint('ck_refund_request_approved_amount_nonneg', 'refund_requests', sa.text('approved_amount IS NULL OR approved_amount >= 0'))

    # 7. Contrainte idempotence webhook : provider_event_id doit être unique
    op.create_unique_constraint('uq_payment_provider_events_provider_event_id', 'payment_provider_events', ['provider_event_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_provider_events_provider_event_id', 'payment_provider_events', type_='unique')
    op.drop_constraint('ck_refund_request_approved_amount_nonneg', 'refund_requests', type_='check')
    op.drop_constraint('ck_refund_request_approved_amount_lte_requested', 'refund_requests', type_='check')
    op.drop_constraint('ck_refund_request_requested_amount_nonneg', 'refund_requests', type_='check')
    op.drop_constraint('ck_payment_intent_amount_paid_nonneg', 'payment_intents', type_='check')
    op.drop_constraint('ck_payment_intent_amount_expected_nonneg', 'payment_intents', type_='check')
    op.drop_constraint('ck_payment_intent_amount_paid_lte_expected', 'payment_intents', type_='check')

    op.alter_column('refund_transactions', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               postgresql_using='amount::double precision')
    op.alter_column('refund_requests', 'approved_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               postgresql_using='approved_amount::double precision')
    op.alter_column('refund_requests', 'requested_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               postgresql_using='requested_amount::double precision')
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               postgresql_using='amount::double precision')
    op.alter_column('payment_intents', 'amount_paid',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               postgresql_using='amount_paid::double precision')
    op.alter_column('payment_intents', 'amount_expected',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               postgresql_using='amount_expected::double precision')
    op.alter_column('payment_intents', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               postgresql_using='amount::double precision')
    # ### end Alembic commands ###
