"""add_logistics_truth_corridor

Revision ID: add_logistics_truth_corridor
Revises: hybrid_dispatch_marketplace
Create Date: 2026-06-03 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_logistics_truth_corridor'
down_revision = 'a5b6c7d8e9f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### Nettoyage : supprimer les doublons de tasks avant d'ajouter la contrainte unique ###
    op.execute("""
        DELETE FROM delivery_tasks a
        USING delivery_tasks b
        WHERE a.id < b.id
        AND a.order_id = b.order_id
        AND a.task_type = b.task_type
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    # Ajouter la contrainte unique sur (order_id, task_type)
    op.create_unique_constraint(
        'uniq_delivery_tasks_order_task_type',
        'delivery_tasks',
        ['order_id', 'task_type']
    )

    # Ajouter l'index sur (driver_id, status)
    op.create_index(
        'idx_delivery_tasks_driver_status',
        'delivery_tasks',
        ['driver_id', 'status'],
        unique=False
    )

    # Créer la table operational_proofs
    op.create_table('operational_proofs',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('proof_type', sa.String(length=50), nullable=False),
        sa.Column('proof_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
        sa.Column('actor_type', sa.String(length=50), nullable=False),
        sa.Column('actor_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('actor_name', sa.String(length=255), nullable=False),
        sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('location_lat', sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column('location_lng', sa.Numeric(precision=11, scale=8), nullable=True),
        sa.Column('location_accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('verification_status', sa.String(length=20), server_default='pending', nullable=False),
        sa.Column('verification_method', sa.String(length=50), nullable=True),
        sa.Column('verification_notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_id'], ['delivery_tasks.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_proofs_order_id'), 'operational_proofs', ['order_id'], unique=False)
    op.create_index(op.f('ix_operational_proofs_task_id'), 'operational_proofs', ['task_id'], unique=False)
    op.create_index(op.f('ix_operational_proofs_proof_type'), 'operational_proofs', ['proof_type'], unique=False)
    op.create_index(op.f('ix_operational_proofs_verification_status'), 'operational_proofs', ['verification_status'], unique=False)

    # Créer la table operational_timelines
    op.create_table('operational_timelines',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('event_subtype', sa.String(length=50), nullable=True),
        sa.Column('from_status', sa.String(length=50), nullable=True),
        sa.Column('to_status', sa.String(length=50), nullable=True),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
        sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('source', sa.String(length=50), nullable=False),
        sa.Column('correlation_id', sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_id'], ['delivery_tasks.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_timelines_order_id'), 'operational_timelines', ['order_id'], unique=False)
    op.create_index(op.f('ix_operational_timelines_task_id'), 'operational_timelines', ['task_id'], unique=False)
    op.create_index('idx_timeline_order_occurred', 'operational_timelines', ['order_id', 'occurred_at'], unique=False)
    op.create_index('idx_timeline_task_occurred', 'operational_timelines', ['task_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timeline_task_occurred', table_name='operational_timelines')
    op.drop_index('idx_timeline_order_occurred', table_name='operational_timelines')
    op.drop_index(op.f('ix_operational_timelines_task_id'), table_name='operational_timelines')
    op.drop_index(op.f('ix_operational_timelines_order_id'), table_name='operational_timelines')
    op.drop_table('operational_timelines')
    op.drop_index(op.f('ix_operational_proofs_verification_status'), table_name='operational_proofs')
    op.drop_index(op.f('ix_operational_proofs_proof_type'), table_name='operational_proofs')
    op.drop_index(op.f('ix_operational_proofs_task_id'), table_name='operational_proofs')
    op.drop_index(op.f('ix_operational_proofs_order_id'), table_name='operational_proofs')
    op.drop_table('operational_proofs')
    op.drop_index('idx_delivery_tasks_driver_status', table_name='delivery_tasks')
    op.drop_constraint('uniq_delivery_tasks_order_task_type', 'delivery_tasks', type_='unique')
    # ### end Alembic commands ###
