"""add_order_version_for_optimistic_locking

Revision ID: add_order_version_for_optimistic_locking
Revises: add_payment_truth_corridor
Create Date: 2026-06-03 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_order_version_locking'
down_revision = 'add_payment_truth_corridor'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('version', sa.Integer(), nullable=True))
    
    # Définir la valeur par défaut pour les lignes existantes
    op.execute("UPDATE orders SET version = 1 WHERE version IS NULL")
    
    # Rendre NOT NULL
    op.alter_column('orders', 'version',
               existing_type=sa.Integer(),
               nullable=False)
    
    # Créer un index sur version pour optimistic locking
    op.create_index('idx_orders_version', 'orders', ['id', 'version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orders_version', table_name='orders')
    op.drop_column('orders', 'version')
    # ### end Alembic commands ###
