"""Create orders module tables

Revision ID: d8c7c8e810cf
Revises: 9e87723373ba
Create Date: 2026-03-15 00:19:43.915501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8c7c8e810cf'
down_revision = '9e87723373ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_name', sa.String(length=255), nullable=False))
    op.add_column('order_items', sa.Column('line_total', sa.Float(), nullable=False))
    op.add_column('order_items', sa.Column('detected_by_ai', sa.Boolean(), nullable=False))
    op.drop_column('order_items', 'total_price')
    op.drop_column('order_items', 'description')
    op.add_column('order_status_history', sa.Column('old_status', sa.String(length=50), nullable=True))
    op.add_column('order_status_history', sa.Column('new_status', sa.String(length=50), nullable=False))
    op.add_column('order_status_history', sa.Column('changed_by_user_id', sa.UUID(), nullable=True))
    op.add_column('order_status_history', sa.Column('change_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'order_status_history', 'users', ['changed_by_user_id'], ['id'])
    op.drop_column('order_status_history', 'notes')
    op.drop_column('order_status_history', 'status')
    op.add_column('orders', sa.Column('payment_status', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('subtotal_amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('pickup_fee', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('delivery_fee', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('pickup_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('pickup_time_slot', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivery_time_slot', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('orders', 'scheduled_delivery_at')
    op.drop_column('orders', 'scheduled_pickup_at')
    op.drop_column('orders', 'actual_pickup_at')
    op.drop_column('orders', 'actual_delivery_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('actual_delivery_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('actual_pickup_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('scheduled_pickup_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('scheduled_delivery_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'completed_at')
    op.drop_column('orders', 'confirmed_at')
    op.drop_column('orders', 'delivery_time_slot')
    op.drop_column('orders', 'delivery_date')
    op.drop_column('orders', 'pickup_time_slot')
    op.drop_column('orders', 'pickup_date')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'pickup_fee')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'subtotal_amount')
    op.drop_column('orders', 'payment_status')
    op.add_column('order_status_history', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('order_status_history', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_status_history', type_='foreignkey')
    op.drop_column('order_status_history', 'change_reason')
    op.drop_column('order_status_history', 'changed_by_user_id')
    op.drop_column('order_status_history', 'new_status')
    op.drop_column('order_status_history', 'old_status')
    op.add_column('order_items', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'detected_by_ai')
    op.drop_column('order_items', 'line_total')
    op.drop_column('order_items', 'item_name')
    # ### end Alembic commands ###