"""create_hybrid_dispatch_marketplace_tables

Revision ID: create_hybrid_dispatch_marketplace_tables
Revises: 79dde77c97d6
Create Date: 2026-03-15 14:06:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'hybrid_dispatch_marketplace'
down_revision = '79dde77c97d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Les types enum ont déjà été créés manuellement
    # Utiliser sa.String avec des contraintes CHECK au lieu de sa.Enum pour éviter les problèmes
    
    # 2. Étendre l'enum DeliveryTaskStatus
    op.execute("ALTER TYPE deliverytaskstatus ADD VALUE 'OPEN_MARKET'")
    op.execute("ALTER TYPE deliverytaskstatus ADD VALUE 'CLAIMED'")
    op.execute("ALTER TYPE deliverytaskstatus ADD VALUE 'DRIVER_ASSIGNED'")
    op.execute("ALTER TYPE deliverytaskstatus ADD VALUE 'EXPIRED'")
    
    # 3. Créer la table delivery_companies
    op.create_table('delivery_companies',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('slug', sa.String(length=200), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('supports_pickup', sa.Boolean(), nullable=False),
        sa.Column('supports_delivery', sa.Boolean(), nullable=False),
        sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column('rating_count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    
    # Ajouter une contrainte CHECK pour la colonne status
    op.execute("""
        ALTER TABLE delivery_companies 
        ADD CONSTRAINT delivery_companies_status_check 
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
    """)
    op.create_index(op.f('ix_delivery_companies_name'), 'delivery_companies', ['name'], unique=True)
    op.create_index(op.f('ix_delivery_companies_slug'), 'delivery_companies', ['slug'], unique=True)
    
    # 4. Créer la table company_drivers
    op.create_table('company_drivers',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('driver_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['delivery_companies.id'], ),
        sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_drivers_company_id'), 'company_drivers', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_drivers_driver_id'), 'company_drivers', ['driver_id'], unique=False)
    
    # 5. Créer la table company_service_zones
    op.create_table('company_service_zones',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('city', sa.String(length=100), nullable=False),
        sa.Column('commune', sa.String(length=100), nullable=True),
        sa.Column('zone', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['delivery_companies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_service_zones_city'), 'company_service_zones', ['city'], unique=False)
    op.create_index(op.f('ix_company_service_zones_company_id'), 'company_service_zones', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_service_zones_commune'), 'company_service_zones', ['commune'], unique=False)
    op.create_index(op.f('ix_company_service_zones_zone'), 'company_service_zones', ['zone'], unique=False)
    
    # 6. Créer la table dispatch_settings
    op.create_table('dispatch_settings',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('scope_type', sa.String(length=20), nullable=False),
        sa.Column('scope_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('dispatch_strategy', sa.String(length=30), nullable=False),
        sa.Column('marketplace_timeout_minutes', sa.Integer(), nullable=False),
        sa.Column('driver_assignment_timeout_minutes', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Ajouter des contraintes CHECK
    op.execute("""
        ALTER TABLE dispatch_settings 
        ADD CONSTRAINT dispatch_settings_scope_type_check 
        CHECK (scope_type IN ('GLOBAL', 'CITY', 'ZONE', 'PARTNER', 'TASK_TYPE'))
    """)
    
    op.execute("""
        ALTER TABLE dispatch_settings 
        ADD CONSTRAINT dispatch_settings_dispatch_strategy_check 
        CHECK (dispatch_strategy IN ('INTERNAL_FIRST', 'MARKETPLACE_FIRST', 'MANUAL_ONLY', 'INTERNAL_ONLY', 'MARKETPLACE_ONLY'))
    """)
    
    op.create_index(op.f('ix_dispatch_settings_scope_id'), 'dispatch_settings', ['scope_id'], unique=False)
    op.create_index(op.f('ix_dispatch_settings_scope_type'), 'dispatch_settings', ['scope_type'], unique=False)
    
    # 7. Ajouter les nouvelles colonnes à delivery_tasks
    op.add_column('delivery_tasks', sa.Column('dispatch_strategy', sa.String(length=30), nullable=True))
    op.add_column('delivery_tasks', sa.Column('dispatch_mode', sa.String(length=30), nullable=True))
    op.add_column('delivery_tasks', sa.Column('assigned_company_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('delivery_tasks', sa.Column('claimed_by_company_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('delivery_tasks', sa.Column('market_visible', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('delivery_tasks', sa.Column('market_opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_tasks', sa.Column('market_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_tasks', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_tasks', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('delivery_tasks', sa.Column('cancel_reason', sa.Text(), nullable=True))
    
    # Ajouter des contraintes CHECK pour les nouvelles colonnes
    op.execute("""
        ALTER TABLE delivery_tasks 
        ADD CONSTRAINT delivery_tasks_dispatch_strategy_check 
        CHECK (dispatch_strategy IS NULL OR dispatch_strategy IN ('INTERNAL_FIRST', 'MARKETPLACE_FIRST', 'MANUAL_ONLY', 'INTERNAL_ONLY', 'MARKETPLACE_ONLY'))
    """)
    
    op.execute("""
        ALTER TABLE delivery_tasks 
        ADD CONSTRAINT delivery_tasks_dispatch_mode_check 
        CHECK (dispatch_mode IS NULL OR dispatch_mode IN ('INTERNAL', 'MARKETPLACE', 'MANUAL_COMPANY', 'MANUAL_DRIVER'))
    """)
    
    # Créer les index et contraintes de clé étrangère
    op.create_index(op.f('ix_delivery_tasks_assigned_company_id'), 'delivery_tasks', ['assigned_company_id'], unique=False)
    op.create_index(op.f('ix_delivery_tasks_claimed_by_company_id'), 'delivery_tasks', ['claimed_by_company_id'], unique=False)
    
    op.create_foreign_key(
        'fk_delivery_tasks_assigned_company_id',
        'delivery_tasks',
        'delivery_companies',
        ['assigned_company_id'],
        ['id']
    )
    
    op.create_foreign_key(
        'fk_delivery_tasks_claimed_by_company_id',
        'delivery_tasks',
        'delivery_companies',
        ['claimed_by_company_id'],
        ['id']
    )
    
    # 8. Insérer les paramètres de dispatch par défaut
    op.execute("""
        INSERT INTO dispatch_settings (
            id, created_at, updated_at, scope_type, scope_id, 
            dispatch_strategy, marketplace_timeout_minutes, 
            driver_assignment_timeout_minutes, is_active
        ) VALUES (
            gen_random_uuid(), NOW(), NOW(), 'GLOBAL', NULL,
            'INTERNAL_FIRST', 30, 15, true
        )
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Supprimer les contraintes de clé étrangère
    op.drop_constraint('fk_delivery_tasks_claimed_by_company_id', 'delivery_tasks', type_='foreignkey')
    op.drop_constraint('fk_delivery_tasks_assigned_company_id', 'delivery_tasks', type_='foreignkey')
    
    # 2. Supprimer les index
    op.drop_index(op.f('ix_delivery_tasks_claimed_by_company_id'), table_name='delivery_tasks')
    op.drop_index(op.f('ix_delivery_tasks_assigned_company_id'), table_name='delivery_tasks')
    
    # 3. Supprimer les colonnes ajoutées à delivery_tasks
    op.drop_column('delivery_tasks', 'cancel_reason')
    op.drop_column('delivery_tasks', 'failure_reason')
    op.drop_column('delivery_tasks', 'claimed_at')
    op.drop_column('delivery_tasks', 'market_expires_at')
    op.drop_column('delivery_tasks', 'market_opened_at')
    op.drop_column('delivery_tasks', 'market_visible')
    op.drop_column('delivery_tasks', 'claimed_by_company_id')
    op.drop_column('delivery_tasks', 'assigned_company_id')
    op.drop_column('delivery_tasks', 'dispatch_mode')
    op.drop_column('delivery_tasks', 'dispatch_strategy')
    
    # 4. Supprimer les tables
    op.drop_table('dispatch_settings')
    op.drop_table('company_service_zones')
    op.drop_table('company_drivers')
    op.drop_table('delivery_companies')
    
    # 5. Supprimer les valeurs d'enum ajoutées (PostgreSQL ne supporte pas DROP VALUE, on recrée l'enum)
    # Pour simplifier, on ne gère pas le downgrade des enums étendus
    
    # 6. Supprimer les enums créés
    op.execute("DROP TYPE IF EXISTS dispatchscopetype")
    op.execute("DROP TYPE IF EXISTS dispatchmode")
    op.execute("DROP TYPE IF EXISTS dispatchstrategy")
    op.execute("DROP TYPE IF EXISTS deliverycompanystatus")
    
    # ### end Alembic commands ###